Drop useless build and test KKM direction from testenv

diff --git a/cloud/aws/Makefile b/cloud/aws/Makefile
--- a/cloud/aws/Makefile
+++ b/cloud/aws/Makefile
@@ -1,16 +1,26 @@
-# placeholder for a real Makefile, just to make it slightly more uniform
-# this is currently used only for KKM testing on AWS
+# A basic Makefile to make KKM AWS test slightly more uniform
+# (this is currently used only for KKM testing on AWS)
+#
+# to run locally, pass IMAGE_VERSION for an existing test pass, e.g.
+# make IMAGE_VERSION=ci-146
 
 TOP := $(shell git rev-parse --show-toplevel)
 
-LOG ?= 0
-PACKER_BUILD = PACKER_LOG=${LOG} time packer build -force
-
 SOURCE_BRANCH ?= $(SRC_BRANCH)
 
-# todo: pass IMAGE_VERSION so proper testenv can be fetched
-test:
-	@echo KKM AWS test. Branch: ${SOURCE_BRANCH} image_version: ${IMAGE_VERSION}
-	SOURCE_BRANCH="${SOURCE_BRANCH}" ${PACKER_BUILD} kkm-test.pkr.hcl
+LOG ?= 0
+PACKER_BUILD = PACKER_LOG=${LOG} time packer build
+
+test: .check_tools ## Test KKM build on AWS using Hashicorp Packer
+	${PACKER_BUILD} \
+		--var source_branch=${SOURCE_BRANCH} \
+		--var image_version=${IMAGE_VERSION} \
+		kkm-test.pkr.hcl
+
+.check_tools:
+	@if ! command -v packer; then \
+		echo -e "${RED}Packer (https://www.packer.io/) is not found. Please install it first${NOCOLOR}" ; \
+		false; \
+	fi
 
 include ${TOP}/make/locations.mk
