Added dep check to java and nokia makefiles

diff --git a/payloads/java/Makefile b/payloads/java/Makefile
--- a/payloads/java/Makefile
+++ b/payloads/java/Makefile
@@ -9,13 +9,15 @@
 #  Kontain Inc.
 #
 # Makefile for building and packing Python payload runtime for KM
+TOP := $(shell git rev-parse --show-cdup)
+COMPONENT := java-11
 
-JDK_VERSION=jdk-11.0.6+10
+JDK_VERSION := jdk-11.0.6+10
+DEP_PACKAGES := java-11-openjdk java-11-openjdk-devel
 
-all:
+all: link
 
-fromsrc: jtreg
-	git clone https://github.com/openjdk/jdk11u.git ${JDK_VERSION} -b ${JDK_VERSION}
+fromsrc: .check ${JDK_VERSION} jtreg ${KM_BIN} ${KM_LDSO}
 	cd ${JDK_VERSION} && bash configure \
 		--disable-warnings-as-errors --with-native-debug-symbols=internal \
 		--with-jvm-variants=server --with-zlib=bundled --with-jtreg=$(realpath jtreg) \
@@ -23,11 +25,28 @@ fromsrc: jtreg
 	make -C ${JDK_VERSION} images
 	./link_km.sh
 
+.PHONY: .check
+.check:
+	@for i in ${DEP_PACKAGES} ; do \
+		if ! rpm -qa | grep $$i -q ; then \
+			failed=1; echo -e "Missing $$i. To install, run \nsudo dnf install $$i" ; \
+		fi ; \
+		if [ -n "$$failed" ] ; then false ; fi \
+	done
+
 link:
 	./link_km.sh
+
+${JDK_VERSION}:
+	git clone https://github.com/openjdk/jdk11u.git ${JDK_VERSION} -b ${JDK_VERSION}
 
 jtreg:
 	tar xf jtreg-4.2-b16.tar.gz
 
-clean:
+clobber:
 	rm -rf jtreg ${JDK_VERSION}
+
+clean:
+	make -C ${JDK_VERSION} clean
+
+include ${TOP}make/images.mk
