Big rework of runtime build, plus support alpine libs in kontain-gcc
* now building with native gcc using musl-specific libs extracted from alpine container
* kontain-gcc uses the above. Dropped specs and use params crafting
* added alpine native (static and dynamic) build on fedora and test under KM
* multiple other fixes, including taste-specific stuff and bugs I stumbled into
* Changes to support alpine libs in kontain-gcc and drop spec
* Many other changes -see readme.md in tests, and comments in files

diff --git a/tools/kontain-gcc b/tools/kontain-gcc
--- a/tools/kontain-gcc
+++ b/tools/kontain-gcc
@@ -1,63 +1,179 @@
-#!/bin/bash
-# Invoke gcc with extra params for Kontain link
-set -e
+#!/bin/bash -e
+#
+# Invoke gcc or g++ with extra params for Kontain link.
+#
+# Links native Alpine binaries (musl with syscalls) or Kontain binaries
+# (musl with hcalls + some functions replacements/stubs/virtualization).
+#
+# Accepts the following extra options:
+# ------------------------------------
+# -kontain|-alpine Which binaries to build. Default 'kontain'
+# -kv              Print a few kontain-specific options and the final gcc command
+# --prefix=dir     Where to look for libs. Default /opt/kontain.This is internal debug option
+#
+# Changes to behavior:
+#--------------------------------------
+# * '-static' is default now, use '-dynamic' or 'shared' to change.
+# * dynlinker and rpath are hardcoded in ELF (Interpreter section, and NEEDED libs)
+#    to point to --prefix (/opt/kontain/ by default)
+# * Some link flags, text segment start and '-no-pie' or '-pie' are forced in some cases (see code below)
+# * A few extra warnings fr flags redundancy/overlaps
+#
+# TODO:
+# * need to add checks/warninga for conflicts around -pie/-nopie and other options we enforces
+
 [ "$TRACE" ] && set -x
 
-TMP_SPEC="/tmp/gcc-${BASHPID}.spec"
-
-function cleanup() {
-   rm -rf ${TMP_SPEC}
-}
-trap cleanup EXIT
-
-cmd=`basename ${BASH_SOURCE[0]}`
-dir=`dirname ${BASH_SOURCE[0]}`
-KM_TOP=`realpath $dir/..`
-PREFIX=/opt/kontain
-KM_LDSO=${PREFIX}/runtime/libc.so
-#check if this is run in local build tree and use the local libs then
-if [[ x${KM_TOP} == x${PREFIX}/* ]] ; then
-   LIB="-L ${PREFIX}/lib64"
-   CRT="${PREFIX}/lib64"
-   SPEC="${PREFIX}/lib64"
-   SHR_LIBC="-L${PREFIX}/lib64 libc.so"
-else
-   LIB="-L ${PREFIX}/lib64 -L ${KM_TOP}/build/runtime"
-   CRT="${KM_TOP}/build/runtime/musl/crt"
-   SPEC="${KM_TOP}"
-   SHR_LIBC="-L${KM_TOP}/build/runtime -l:libc.so"
-fi
-SHR_LIBSTDCPP=
-
-if [[ $cmd == *g++ ]] ; then
+cmd=${BASH_SOURCE[0]}
+if [[ $cmd == *c++ || $cmd == *g++ ]] ; then
     REALGCC=g++
-    SHR_LIBSTDCPP="/opt/kontain/lib64/libstdc++.so /opt/kontain/lib64/libgcc_s.so.1"
 else
     REALGCC=gcc
 fi
 if [[ $# -eq 0 ]] ; then exec "${REALGCC}" ; fi
 
-cat <<EOF > ${TMP_SPEC}
-%rename link old_link
+function cleanup() {
+   # placeholder
+   true
+}
+trap cleanup EXIT
 
-*cc1:
-%{!shared: -no-pie} %{shared: -fPIC}
+cmd=$(basename ${BASH_SOURCE[0]})
+dir=$(dirname ${BASH_SOURCE[0]})
+TOP=$(realpath $dir/..)
+PREFIX=/opt/kontain
 
-*lib:
-%{!shared: -lruntime -lpthread -lruntime} %{shared: -lc}
+# Note: the /opt/kontain/runtime/libc.so is hardcoded in GDB support, so when using
+# from other locations some shared lib GDB files location may break
+KM_LDSO=${PREFIX}/runtime/libc.so
 
-*libgcc:
-%{shared: libgcc_s.so%s} libgcc.a%s %:if-exists(libgcc_eh.a%s)
+# defaults
+target=kontain
+type=static
 
-*startfile:
-%{!shared: ${CRT}/crt1.o%s} %{shared: ${CRT}/Scrt1.o } ${CRT}/x86_64/crti.o%s %{!shared: crtbeginT.o%s} %{shared: crtbeginS.o%s}
+# now check the args
+for arg in "$@"
+do
+   case "$arg" in
+      -static|-dynamic|-shared)
+         type="${1#*-}"
+         if [[ -n $type_set && $type != $type_set ]] ; then
+            echo "Warning: type was already set to '$type_set', resetting to '$1'"
+         fi
+         type_set=$type
+         ;;
+      -alpine|-kontain)
+         target="${1#*-}"
+         if [[ -n $target_set && $target != $target_set ]] ; then
+            echo "Warning: type was already set to '$target_set', resetting to '$1'"
+         fi
+         target_set=$target
+         ;;
+      --prefix=*)
+         PREFIX="${1#*=}"
+         ;;
+      -kv)
+         verbose=1
+         ;;
+      # TODO: use this to check some args for sanity
+      -no-pie)
+         no_pie_requested=1
+         cargs="$cargs \"$arg\""
+         ;;
+      -pie)
+         pie_requested=1
+         cargs="$cargs \"$arg\""
+         ;;
+      *)
+         cargs="$cargs \"$arg\""
+         ;;
+    esac
+    shift
+done
 
-*endfile:
-%{!shared: crtend.o%s} %{shared: crtendS.o%s} ${CRT}/x86_64/crtn.o%s
+if [ ! -d $PREFIX ] ; then
+   echo "Error: $PREFIX directory not found"
+   exit 1
+fi
 
-*link:
-%(old_link) %{!shared:%{!rdynamic:-static} -Ttext-segment=0x200000 -e_start} %{rdynamic:--rpath=${PREFIX}/lib64 --dynamic-linker=${KM_LDSO} ${SHR_LIBC} ${SHR_LIBSTDCPP} -export-dynamic} -u__km_interrupt_table -u__km_sigreturn -u__km_handle_interrupt -u __km_syscall_handler --gc-sections -zseparate-code -znorelro -zmax-page-size=0x1000
+RT=${PREFIX}/runtime
+LC=${PREFIX}/alpine-lib/usr/lib
+LL=${PREFIX}/alpine-lib/lib
+# NOTE:
+# * this depends on gcc version in alpine contaier (see tests/alpine-lib.dockerfile)
+# * this has to match with LIBGCC path in locations.mk
+LGCC=${PREFIX}/alpine-lib/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0
+
+# For both static and dynamic buids, locations to scout for libs, and common flags
+ALPINE_PATH="-B${LL} -B${LC} -B${LGCC}"
+HCALL_PATH="-B${RT} ${ALPINE_PATH} -zseparate-code -zmax-page-size=0x1000"
+
+# rpath for dynamic builds
+HCALL_RPATH="-Wl,-rpath=${RT} -Wl,-rpath=${LC} -Wl,-rpath=${LGCC}"
+ALPINE_RPATH="-Wl,-rpath=${LC} -Wl,-rpath=${LGCC}"
+
+# Flags for building kontain (hypercall-based) unikernels
+HCALL_STATIC="-static   ${HCALL_PATH}                -no-pie -Wl,-Ttext-segment=0x200000 -Wl,--gc-sections"
+HCALL_DYNAMIC="-dynamic ${HCALL_PATH} ${HCALL_RPATH} -no-pie -Wl,-Ttext-segment=0x200000 -Wl,--dynamic-linker=${RT}/libc.so"
+HCALL_SHARED="-shared   ${HCALL_PATH} ${HCALL_RPATH} -pie "
+
+# Flags for alpine native and kontain (hcall) builds
+# Note: Alpine native dynamic work under KM only if built with explicit --pie or --Ttext-segment
+ALPINE_STATIC="-static ${ALPINE_PATH}"
+ALPINE_DYNAMIC="-dynamic ${ALPINE_PATH} ${ALPINE_RPATH} -pie -Wl,--dynamic-linker=${LL}/ld-musl-x86_64.so.1"
+# not tested:
+APLINE_SHARED="-shared ${ALPINE_PATH} ${ALPINE_RPATH}"
+
+# pure paranoia - check targets and libs
+if [[ $target != alpine && $target != kontain ]] ; then
+      echo "Error: Unknown target: $target (only alpine and kontain are supported)"
+      exit 1
+fi
+for lib in ${RT}/libruntime.a ${RT}/libc.a  ${RT}/libc.so ${LC}/libc.so ${LC}/libc.so; do
+   if [ ! -r $lib ] ; then
+      echo "Error: can't find $lib - check installation"
+      exit 1
+   fi
+done
+
+
+# Now set correct search paths and args
+case $type in
+   static)
+      if [[ $target = kontain ]] ; then
+         KARGS=$HCALL_STATIC
+      else
+         KARGS=$ALPINE_STATIC
+      fi
+      ;;
+   dynamic)
+      if [[ $target = kontain ]] ; then
+         KARGS=$HCALL_DYNAMIC
+      else
+         KARGS=$ALPINE_DYNAMIC
+      fi
+      ;;
+   shared)
+      if [[ $target = kontain ]] ; then
+         KARGS=$HCALL_SHARED
+      else
+         echo "Warning: alpine -shared was not tested"
+         KARGS=$APLINE_SHARED
+      fi
+      ;;
+esac
+
+if [[ -n "$KARGS" ]] ; then
+   cargs="$KARGS $cargs"
+fi
+
+if [ -n "$verbose" ] ; then
+   cat <<EOF
+$(basename $0): Compiler='${REALGCC}', -type='$type', -target='$target', --prefix='$PREFIX'
+$(basename $0): pie_requested='$pie_requested' nopie_requested='$no_pie_requested' kverbose='$verbose'"
+$(basename $0): Command: ${REALGCC} $cargs
+
 EOF
+fi
 
-"${REALGCC}" -specs=${TMP_SPEC} "$@" ${LIB}
-
+eval "${REALGCC}" "$cargs"
