passing needs to callable workflow

diff --git a/.github/workflows/km-ci-coverage.yaml b/.github/workflows/km-ci-coverage.yaml
--- a/.github/workflows/km-ci-coverage.yaml
+++ b/.github/workflows/km-ci-coverage.yaml
@@ -97,6 +97,11 @@ jobs:
 
       - uses: actions/checkout@v2
 
+      - name: Force failrure
+        run: |
+          echo "::error"
+          exit 1
+
       - name: Login to Azure Repository
         run: make -C cloud/azure login-cli
 
@@ -207,4 +212,6 @@ jobs:
     if: always()
     needs: [start-runners, coverage-azure, coverage-ec2]
     uses: ./.github/workflows/stop-cloud-runners.yaml
+    with:
+      needs: ${{needs}}
     secrets: inherit
